<a href="https://colab.research.google.com/github/kdzioba/machine-learning-bootcamp/blob/main/regresja_liniowa/02_gradient.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np
import pandas as pd
import plotly.express as px

np.random.seed(42)

Przygotowanie danych

In [19]:
X1 = np.array([1, 2, 3, 4, 5, 6])
Y = np.array([3000, 3250, 3500, 3750, 4000, 4250])
m = len(X1)

print(f'Lata pracy: {X1}')
print(f'Wynagrodzenie: {Y}')
print(f'Liczba próbek: {m}')

Lata pracy: [1 2 3 4 5 6]
Wynagrodzenie: [3000 3250 3500 3750 4000 4250]
Liczba próbek: 6


In [20]:
X1 = X1.reshape(m, 1)
print(X1)
print(X1.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [21]:
bias = np.ones((m, 1))
print(bias)
print(bias.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(6, 1)


In [22]:
X = np.append(bias, X1, axis=1)
print(X)
print(X.shape)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
(6, 2)


In [24]:
Y = Y.reshape(-1, 1)
print(Y)
print(Y.shape)

[[3000]
 [3250]
 [3500]
 [3750]
 [4000]
 [4250]]
(6, 1)


Równanie normalne


In [6]:
L = np.linalg.inv(np.dot(X.T, X))
L

array([[ 0.86666667, -0.2       ],
       [-0.2       ,  0.05714286]])

In [7]:
P = np.dot(X.T, Y)
P

array([21750., 80500.])

In [8]:
np.dot(L, P)

array([2750.,  250.])

Regresja liniowa przy pomocy scikit-learn

In [9]:
from sklearn.linear_model import LinearRegression

regression = LinearRegression()
regression.fit(X1, Y)

print(regression.intercept_)
print(regression.coef_[0])

2750.0
250.0


Metoda gradientu prostego

### 1. Losowa inicjalizacja parametrów

In [38]:
eta = 0.01

weights = np.random.randn(2, 1)
print(X)
print(weights)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
[[1.57921282]
 [0.76743473]]


In [39]:
intercept = []
coef = []

for i in range(5000):
    gradient = (2 / m) * X.T.dot(X.dot(weights) - Y)
    weights = weights - eta * gradient
    intercept.append(weights[0][0])
    coef.append(weights[1][0])

print(weights)

[[2749.99997065]
 [ 250.00000685]]


In [40]:
df = pd.DataFrame(data={'intercept': intercept, 'coef': coef})
df.head()

intercept        coef
0   73.993908  268.757435
1  126.201010  450.388106
2  164.649822  573.269643
3  193.727950  656.185697
4  216.420393  711.915079

In [41]:
px.line(df, y='intercept', width=800, title='Dopasowanie: intercept')

In [42]:
px.line(df, y='coef', width=800, title='Dopasowanie: coef')